version: '3'

services:
  mysql:
    image: mysql:8.0.29
    volumes:
    - ./schemas/create-table-macapa.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=macapa
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  postgres:
    image: postgres
    volumes:
    - ./schemas/create-table-varejao.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "varejao"

  api:
    depends_on:
    - mysql
    - postgres
    build:
      dockerfile: docker/Dockerfile
      context: ./
    ports:
     - "8082:8082"